[build]
  # Directorio donde se construye la aplicación
  base = "."
  
  # Comando para construir la aplicación
  command = "npm run build"
  
  # Directorio donde se generan los archivos estáticos
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Configuración de redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para archivos HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
